Add more flexibility by not decorating default controller
silasjoisten/sonata-multiupload-bundle pull request #155
Opened 2022-05-15 05:40 UTC by mpoiriert

This will allow to override the create method even if we are using another controller for the admin.

Also the decorates is not implemented properly since you must call all the methods of the original decorated controller (the MediaAdminController does override the listAction).

It's better to not decorate in this case.

2022-05-15 05:41 UTC, mpoiriert commented
We could also consider renaming the controller MediaAdminController for CreateController to follow naming convetion of "MultiUploadController"

2022-05-15 08:00 UTC, silasjoisten requested changes

2022-05-15 08:05 UTC, silasjoisten commented
@mpoiriert have you tested it?

2022-05-15 11:46 UTC, mpoiriert commented
@silasjoisten I have rename the controller.

I did also change the MultiUploadController to rely on "$this->admin" instead of injecting the MediaAdmin. This remove code and allow to have a custom Media Admin instead of forcing use to use the provided MediaAdmin.

I have use my branch directly in my project so I do confirm it's working.

2022-05-15 19:05 UTC, silasjoisten commented on src/Resources/config/controller.yaml
> +        tags: [ 'container.service_subscriber']
```suggestion
        tags: [ 'container.service_subscriber' ]
```

2022-05-15 19:06 UTC, silasjoisten commented
Nice great Job! Thanks a lot only this small change i suggested then i merge it and release it

2022-05-15 22:47 UTC, mpoiriert commented on src/Resources/config/controller.yaml
> +        tags: [ 'container.service_subscriber']
Sorry about that

2022-05-16 06:25 UTC, silasjoisten approved these changes

2022-05-16 06:26 UTC, merged

2022-05-16 06:26 UTC, silasjoisten commented
@mpoiriert Thank you!

2022-05-16 06:29 UTC, silasjoisten commented
released in [4.0.1](https://github.com/silasjoisten/sonata-multiupload-bundle/releases/tag/4.0.1)